### ISSUE TITLE
singlemd fails with string conversion error

### ISSUE THREAD

**Issue by karthick-core** [snesjhon/singlemd#2]
18
$ npm install singlemd -g
19 /usr/local/bin/singlemd -> /usr/local/lib/node_modules/singlemd/bin/singlemd
20 + singlemd@0.0.4
21 added 83 packages from 326 contributors in 4.491s
22 $ singlemd --input ./README.md --output index.html --style ./style.css
23 /usr/local/lib/node_modules/singlemd/cmds/render.js:51
24 						$('#md-style').append(data.toString());
25 						                           ^
26 TypeError: Cannot read property 'toString' of undefined
27     at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/singlemd/cmds/render.js:51:34)
28     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
29 ERROR: Job failed: exit code 1

**Comment by snesjhon** [comment]
Interesting. Will check. Thank you for submitting
